
# Gem::Specification for Ipt-0.0.3
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: ipt
version: !ruby/object:Gem::Version 
  version: 0.0.3
platform: ruby
authors: 
- Angel Pizarro
autorequire: 
bindir: bin

date: 2009-04-23 00:00:00 -04:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: hpricot
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - "="
      - !ruby/object:Gem::Version 
        version: "0.6"
    version: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: Proteomics utilities
email: angel@mail.med.upenn.edu
executables: 
- fix_deconmsn.rb
- map_cluster.rb
- mgf2dta
- post_deconmsn.rb
- post_mscluster.rb
- run_deconmsn.rb
- run_extractmsn.rb
- run_mscluster.rb
extensions: []

extra_rdoc_files: 
- bin/fix_deconmsn.rb
- bin/map_cluster.rb
- bin/mgf2dta
- bin/post_deconmsn.rb
- bin/post_mscluster.rb
- bin/run_deconmsn.rb
- bin/run_extractmsn.rb
- bin/run_mscluster.rb
- CHANGELOG
- lib/ipt/parsers/mgf.rb
- lib/ipt/parsers/mzxml.rb
- lib/ipt/parsers/pepxml.rb
- lib/ipt/parsers/protxml.rb
- lib/ipt/parsers.rb
- lib/ipt.rb
- LICENSE
- README.rdoc
files: 
- bin/fix_deconmsn.rb
- bin/map_cluster.rb
- bin/mgf2dta
- bin/post_deconmsn.rb
- bin/post_mscluster.rb
- bin/run_deconmsn.rb
- bin/run_extractmsn.rb
- bin/run_mscluster.rb
- CHANGELOG
- ipt.gemspec
- lib/ipt/parsers/mgf.rb
- lib/ipt/parsers/mzxml.rb
- lib/ipt/parsers/pepxml.rb
- lib/ipt/parsers/protxml.rb
- lib/ipt/parsers.rb
- lib/ipt.rb
- LICENSE
- Manifest
- Rakefile
- README.rdoc
has_rdoc: true
homepage: ""
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Ipt
- --main
- README.rdoc
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: ipt
rubygems_version: 1.2.0
specification_version: 2
summary: Proteomics utilities
test_files: []
